spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5436/spribe-db
    username: myuser
    password: secret
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

app:
  exchange-server:
    url: https://openexchangerates.org/api/
    app-id: 512c58dceca743249cf9230badeb31cc