spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/spribe-db
    username: myuser
    password: secret
  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG