spring:
  application:
    name: spribe-demo
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  threads:
    virtual:
      enabled: true


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health" ]
  endpoint:
    health:
      show-details: always

app:
  exchange-server:
    app-id: ${EXCHANGE_SERVER_APP_ID}
    url: ${EXCHANGE_SERVER_URL}